times = ('Flamengo', 'botafogo', 'corinthias', 'fluminence', 'vasco')
print("=="*20)
print(f'Lista de times: {times}')
print("=="*20)
print(f'Os primeiros colocados são {times[0:3]}')
print("=="*20)
print(f'Os últimos colocados foram {times[3:5]}')
print("=="*20)
print(f'Em ordem alfabética: {sorted(times)}')
print("=="*20)
print(f'A posição de fluminence é {times.index("fluminence")+1} posição')